#!/bin/bash
# Generates src/buildInfo.ts with the current git commit hash and timestamp.
set -euo pipefail

COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
DATE=$(date '+%Y-%m-%d %H:%M')

cat > src/buildInfo.ts << EOF
// Auto-generated by scripts/generate-build-info.sh — do not edit manually.
export const BUILD_COMMIT = '${COMMIT}';
export const BUILD_DATE = '${DATE}';
EOF

echo "Build info: ${COMMIT} @ ${DATE}"
