// Auto-generated by scripts/generate-build-info.sh — do not edit manually.
// Fallback values used during development; overwritten at build time.
export const BUILD_COMMIT = 'dev';
export const BUILD_DATE = 'dev';
